apiVersion: v1
kind: ReplicationController
metadata:
  name: os-signal
spec:
  replicas: 1
  selector:
    app: os-signal
  template:
    metadata:
      name: os-signal
      labels:
        app: os-signal
    spec:
      containers:
      - name: os-signal
        image: sadlil/os-signal:demo
        imagePullPolicy: Always